// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ConfigUser struct {
	Name       *string  `json:"name,omitempty"`
	Endpoint   string   `json:"endpoint"`
	Secret     *string  `json:"secret,omitempty"`
	EventTypes []string `json:"eventTypes"`
}

func (o *ConfigUser) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ConfigUser) GetEndpoint() string {
	if o == nil {
		return ""
	}
	return o.Endpoint
}

func (o *ConfigUser) GetSecret() *string {
	if o == nil {
		return nil
	}
	return o.Secret
}

func (o *ConfigUser) GetEventTypes() []string {
	if o == nil {
		return []string{}
	}
	return o.EventTypes
}
