// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/webhooks/pkg/client/internal/utils"
	"time"
)

type Delivery struct {
	ID             string  `json:"id"`
	EventID        string  `json:"eventID"`
	IdempotencyKey *string `json:"idempotencyKey,omitempty"`
	ConfigID       string  `json:"configID"`
	EventType      string  `json:"eventType"`
	// Present only on delivery detail responses.
	Payload          *string        `json:"payload,omitempty"`
	Status           DeliveryStatus `json:"status"`
	AttemptCount     int64          `json:"attemptCount"`
	ReplayGeneration int64          `json:"replayGeneration"`
	CycleStartedAt   *time.Time     `json:"cycleStartedAt,omitempty"`
	NextAttemptAt    *time.Time     `json:"nextAttemptAt,omitempty"`
	ClaimedAt        *time.Time     `json:"claimedAt,omitempty"`
	LastAttemptAt    *time.Time     `json:"lastAttemptAt,omitempty"`
	LastStatusCode   *int64         `json:"lastStatusCode,omitempty"`
	LastError        *string        `json:"lastError,omitempty"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
}

func (d Delivery) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *Delivery) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Delivery) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Delivery) GetEventID() string {
	if o == nil {
		return ""
	}
	return o.EventID
}

func (o *Delivery) GetIdempotencyKey() *string {
	if o == nil {
		return nil
	}
	return o.IdempotencyKey
}

func (o *Delivery) GetConfigID() string {
	if o == nil {
		return ""
	}
	return o.ConfigID
}

func (o *Delivery) GetEventType() string {
	if o == nil {
		return ""
	}
	return o.EventType
}

func (o *Delivery) GetPayload() *string {
	if o == nil {
		return nil
	}
	return o.Payload
}

func (o *Delivery) GetStatus() DeliveryStatus {
	if o == nil {
		return DeliveryStatus("")
	}
	return o.Status
}

func (o *Delivery) GetAttemptCount() int64 {
	if o == nil {
		return 0
	}
	return o.AttemptCount
}

func (o *Delivery) GetReplayGeneration() int64 {
	if o == nil {
		return 0
	}
	return o.ReplayGeneration
}

func (o *Delivery) GetCycleStartedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CycleStartedAt
}

func (o *Delivery) GetNextAttemptAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.NextAttemptAt
}

func (o *Delivery) GetClaimedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ClaimedAt
}

func (o *Delivery) GetLastAttemptAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastAttemptAt
}

func (o *Delivery) GetLastStatusCode() *int64 {
	if o == nil {
		return nil
	}
	return o.LastStatusCode
}

func (o *Delivery) GetLastError() *string {
	if o == nil {
		return nil
	}
	return o.LastError
}

func (o *Delivery) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Delivery) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
