// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeliveryResponse struct {
	Data Delivery `json:"data"`
}

func (o *DeliveryResponse) GetData() Delivery {
	if o == nil {
		return Delivery{}
	}
	return o.Data
}
