// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeliveryAttemptsResponseCursor struct {
	PageSize *int64            `json:"pageSize,omitempty"`
	HasMore  bool              `json:"hasMore"`
	Next     *string           `json:"next,omitempty"`
	Data     []DeliveryAttempt `json:"data"`
}

func (o *DeliveryAttemptsResponseCursor) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *DeliveryAttemptsResponseCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *DeliveryAttemptsResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *DeliveryAttemptsResponseCursor) GetData() []DeliveryAttempt {
	if o == nil {
		return []DeliveryAttempt{}
	}
	return o.Data
}

type DeliveryAttemptsResponse struct {
	Cursor DeliveryAttemptsResponseCursor `json:"cursor"`
}

func (o *DeliveryAttemptsResponse) GetCursor() DeliveryAttemptsResponseCursor {
	if o == nil {
		return DeliveryAttemptsResponseCursor{}
	}
	return o.Cursor
}
