// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/formancehq/webhooks/pkg/client/internal/utils"
	"time"
)

type Outcome string

const (
	OutcomeSucceeded        Outcome = "succeeded"
	OutcomeRetryableFailure Outcome = "retryable_failure"
	OutcomePermanentFailure Outcome = "permanent_failure"
)

func (e Outcome) ToPointer() *Outcome {
	return &e
}
func (e *Outcome) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "succeeded":
		fallthrough
	case "retryable_failure":
		fallthrough
	case "permanent_failure":
		*e = Outcome(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Outcome: %v", v)
	}
}

type DeliveryAttempt struct {
	ID               string    `json:"id"`
	DeliveryID       string    `json:"deliveryID"`
	AttemptNumber    int64     `json:"attemptNumber"`
	ReplayGeneration int64     `json:"replayGeneration"`
	Endpoint         string    `json:"endpoint"`
	Outcome          Outcome   `json:"outcome"`
	StatusCode       int64     `json:"statusCode"`
	Error            *string   `json:"error,omitempty"`
	DurationMillis   *int64    `json:"durationMillis,omitempty"`
	ResponseExcerpt  *string   `json:"responseExcerpt,omitempty"`
	CreatedAt        time.Time `json:"createdAt"`
}

func (d DeliveryAttempt) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeliveryAttempt) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DeliveryAttempt) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DeliveryAttempt) GetDeliveryID() string {
	if o == nil {
		return ""
	}
	return o.DeliveryID
}

func (o *DeliveryAttempt) GetAttemptNumber() int64 {
	if o == nil {
		return 0
	}
	return o.AttemptNumber
}

func (o *DeliveryAttempt) GetReplayGeneration() int64 {
	if o == nil {
		return 0
	}
	return o.ReplayGeneration
}

func (o *DeliveryAttempt) GetEndpoint() string {
	if o == nil {
		return ""
	}
	return o.Endpoint
}

func (o *DeliveryAttempt) GetOutcome() Outcome {
	if o == nil {
		return Outcome("")
	}
	return o.Outcome
}

func (o *DeliveryAttempt) GetStatusCode() int64 {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeliveryAttempt) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *DeliveryAttempt) GetDurationMillis() *int64 {
	if o == nil {
		return nil
	}
	return o.DurationMillis
}

func (o *DeliveryAttempt) GetResponseExcerpt() *string {
	if o == nil {
		return nil
	}
	return o.ResponseExcerpt
}

func (o *DeliveryAttempt) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}
