// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeliveriesResponseCursor struct {
	PageSize *int64     `json:"pageSize,omitempty"`
	HasMore  bool       `json:"hasMore"`
	Next     *string    `json:"next,omitempty"`
	Data     []Delivery `json:"data"`
}

func (o *DeliveriesResponseCursor) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *DeliveriesResponseCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *DeliveriesResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *DeliveriesResponseCursor) GetData() []Delivery {
	if o == nil {
		return []Delivery{}
	}
	return o.Data
}

type DeliveriesResponse struct {
	Cursor DeliveriesResponseCursor `json:"cursor"`
}

func (o *DeliveriesResponse) GetCursor() DeliveriesResponseCursor {
	if o == nil {
		return DeliveriesResponseCursor{}
	}
	return o.Cursor
}
