// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ReplayDeliveriesResponse struct {
	Data ReplayDeliveriesResult `json:"data"`
}

func (o *ReplayDeliveriesResponse) GetData() ReplayDeliveriesResult {
	if o == nil {
		return ReplayDeliveriesResult{}
	}
	return o.Data
}
