// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/webhooks/pkg/client/internal/utils"
	"time"
)

type ReplayDeliveriesResult struct {
	Replayed    int64     `json:"replayed"`
	Expedited   int64     `json:"expedited"`
	Skipped     int64     `json:"skipped"`
	HasMore     bool      `json:"hasMore"`
	NextCursor  *string   `json:"nextCursor,omitempty"`
	CreatedAtTo time.Time `json:"createdAtTo"`
}

func (r ReplayDeliveriesResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReplayDeliveriesResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ReplayDeliveriesResult) GetReplayed() int64 {
	if o == nil {
		return 0
	}
	return o.Replayed
}

func (o *ReplayDeliveriesResult) GetExpedited() int64 {
	if o == nil {
		return 0
	}
	return o.Expedited
}

func (o *ReplayDeliveriesResult) GetSkipped() int64 {
	if o == nil {
		return 0
	}
	return o.Skipped
}

func (o *ReplayDeliveriesResult) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *ReplayDeliveriesResult) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *ReplayDeliveriesResult) GetCreatedAtTo() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAtTo
}
