// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/formancehq/webhooks/pkg/client/internal/utils"
	"time"
)

type Statuses string

const (
	StatusesFailed  Statuses = "failed"
	StatusesPending Statuses = "pending"
)

func (e Statuses) ToPointer() *Statuses {
	return &e
}
func (e *Statuses) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "failed":
		fallthrough
	case "pending":
		*e = Statuses(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Statuses: %v", v)
	}
}

type ReplayDeliveriesRequest struct {
	CreatedAtFrom time.Time  `json:"createdAtFrom"`
	CreatedAtTo   *time.Time `json:"createdAtTo,omitempty"`
	Statuses      []Statuses `json:"statuses,omitempty"`
	ConfigIds     []string   `json:"configIds,omitempty"`
	Cursor        *string    `json:"cursor,omitempty"`
	PageSize      *int64     `default:"1000" json:"pageSize"`
}

func (r ReplayDeliveriesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReplayDeliveriesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ReplayDeliveriesRequest) GetCreatedAtFrom() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAtFrom
}

func (o *ReplayDeliveriesRequest) GetCreatedAtTo() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAtTo
}

func (o *ReplayDeliveriesRequest) GetStatuses() []Statuses {
	if o == nil {
		return nil
	}
	return o.Statuses
}

func (o *ReplayDeliveriesRequest) GetConfigIds() []string {
	if o == nil {
		return nil
	}
	return o.ConfigIds
}

func (o *ReplayDeliveriesRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *ReplayDeliveriesRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}
