openapi: 3.0.3
info:
  title: Webhooks server
  version: 0.0.0
paths:
  /_healthcheck:
    get:
      summary: Health check of the server.
      operationId: healthCheck
      tags:
        - Health check
      responses:
        "200":
          description: The server is healthy.
          content: {}

  /configs:
    get:
      summary: Get all configs, sorted by modification date descending.
      operationId: getAllConfigs
      tags:
        - Configs
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - cursor
                properties:
                  cursor:
                    allOf:
                      - $ref: '#/components/schemas/Cursor'
                      - type: object
                        properties:
                          data:
                            type: array
                            items:
                              $ref: '#/components/schemas/ConfigInserted'
                        required:
                          - data

    post:
      summary: |
        Insert a new config.
      description: |
        Insert a new config. 
        
        The secret is the endpoint's verification secret. 
        If not passed or empty, a secret is automatically generated. 
        The format is a random string of bytes of size 24, base64 encoded. (larger size after encoding)
      operationId: insertOneConfig
      tags:
        - Configs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - cursor
                properties:
                  cursor:
                    allOf:
                      - $ref: '#/components/schemas/Cursor'
                      - type: object
                        properties:
                          data:
                            type: array
                            items:
                              $ref: '#/components/schemas/ConfigInserted'
                        required:
                          - data
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
                example: endpoints should be valid urls

    delete:
      summary: Delete one config.
      operationId: deleteOneConfig
      tags:
        - Configs
      parameters:
        - name: id
          in: path
          description: Config ID
          required: true
          schema:
            type: string
            example: 4997257d-dfb6-445b-929c-cbe2ab182818
      responses:
        "200":
          description: OK
          content: {}

  /configs/{id}/activate:
    put:
      summary: Activate one config.
      operationId: activateOneConfig
      tags:
        - Configs
      parameters:
        - name: id
          in: path
          description: Config ID
          required: true
          schema:
            type: string
            example: 4997257d-dfb6-445b-929c-cbe2ab182818
      responses:
        "200":
          description: OK
          content: {}

  /configs/{id}/deactivate:
    put:
      summary: Deactivate one config.
      operationId: deactivateOneConfig
      tags:
        - Configs
      parameters:
        - name: id
          in: path
          description: Config ID
          required: true
          schema:
            type: string
            example: 4997257d-dfb6-445b-929c-cbe2ab182818
      responses:
        "200":
          description: OK
          content: {}

  /configs/{id}/secret/rotate:
    put:
      summary: Rotates the config's endpoint's signing secret.
      description: |
        Rotates the config's endpoint's signing secret. The previous secret will be valid for the next 24 hours.
        
        If not passed or empty, a secret is automatically generated. 
        The format is a random string of bytes of size 24, base64 encoded. (larger size after encoding)
      operationId: rotateOneConfigSecret
      tags:
        - Configs
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                secret:
                  type: string
                  example: "V0bivxRWveaoz08afqjU6Ko/jwO0Cb+3"
                  required: false
      parameters:
        - name: id
          in: path
          description: Config ID
          required: true
          schema:
            type: string
            example: 4997257d-dfb6-445b-929c-cbe2ab182818
      responses:
        "200":
          description: OK
          content: {}

components:
  schemas:
    Config:
      properties:
        endpoint:
          type: string
          example: "https://example.com"
        secret:
          type: string
          example: "V0bivxRWveaoz08afqjU6Ko/jwO0Cb+3"
        eventTypes:
          type: array
          items:
            type: string
            example: "TYPE1"
          example: ["TYPE1", "TYPE2"]

    ConfigInserted:
      properties:
        endpoint:
          type: string
          example: "https://example.com"
        secret:
          type: string
          example: "V0bivxRWveaoz08afqjU6Ko/jwO0Cb+3"
        eventTypes:
          type: array
          items:
            type: string
            example: "TYPE1"
          example: ["TYPE1", "TYPE2"]
        active:
          type: boolean
          example: true
        createdAt:
          type: string
          format: date-time
          example: "2022-07-20T07:31:40Z"
        modifiedAt:
          type: string
          format: date-time
          example: "2022-07-20T08:32:59Z"

    Cursor:
      type: object
      properties:
        has_more:
          type: boolean
          example: false
