// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/webhooks/pkg/client/models/components"
)

type ChangeConfigSecretRequest struct {
	// Config ID
	ID                 string                         `pathParam:"style=simple,explode=false,name=id"`
	ConfigChangeSecret *components.ConfigChangeSecret `request:"mediaType=application/json"`
}

func (o *ChangeConfigSecretRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ChangeConfigSecretRequest) GetConfigChangeSecret() *components.ConfigChangeSecret {
	if o == nil {
		return nil
	}
	return o.ConfigChangeSecret
}

type ChangeConfigSecretResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Secret successfully changed.
	ConfigResponse *components.ConfigResponse
}

func (o *ChangeConfigSecretResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ChangeConfigSecretResponse) GetConfigResponse() *components.ConfigResponse {
	if o == nil {
		return nil
	}
	return o.ConfigResponse
}
