// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/webhooks/pkg/client/models/components"
)

type DeactivateConfigRequest struct {
	// Config ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeactivateConfigRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DeactivateConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Config successfully deactivated.
	ConfigResponse *components.ConfigResponse
}

func (o *DeactivateConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeactivateConfigResponse) GetConfigResponse() *components.ConfigResponse {
	if o == nil {
		return nil
	}
	return o.ConfigResponse
}
