// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/webhooks/pkg/client/internal/utils"
	"github.com/formancehq/webhooks/pkg/client/models/components"
	"time"
)

type GetDeliveriesRequest struct {
	ConfigID      *string                    `queryParam:"style=form,explode=true,name=configId"`
	Status        *components.DeliveryStatus `queryParam:"style=form,explode=true,name=status"`
	CreatedAtFrom *time.Time                 `queryParam:"style=form,explode=true,name=createdAtFrom"`
	CreatedAtTo   *time.Time                 `queryParam:"style=form,explode=true,name=createdAtTo"`
	Cursor        *string                    `queryParam:"style=form,explode=true,name=cursor"`
	PageSize      *int64                     `default:"100" queryParam:"style=form,explode=true,name=pageSize"`
}

func (g GetDeliveriesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetDeliveriesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetDeliveriesRequest) GetConfigID() *string {
	if o == nil {
		return nil
	}
	return o.ConfigID
}

func (o *GetDeliveriesRequest) GetStatus() *components.DeliveryStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *GetDeliveriesRequest) GetCreatedAtFrom() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAtFrom
}

func (o *GetDeliveriesRequest) GetCreatedAtTo() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAtTo
}

func (o *GetDeliveriesRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *GetDeliveriesRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type GetDeliveriesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated deliveries without payloads.
	DeliveriesResponse *components.DeliveriesResponse
}

func (o *GetDeliveriesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetDeliveriesResponse) GetDeliveriesResponse() *components.DeliveriesResponse {
	if o == nil {
		return nil
	}
	return o.DeliveriesResponse
}
