// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/webhooks/pkg/client/models/components"
)

type GetDeliveryRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetDeliveryRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetDeliveryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Delivery detail including its payload.
	DeliveryResponse *components.DeliveryResponse
}

func (o *GetDeliveryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetDeliveryResponse) GetDeliveryResponse() *components.DeliveryResponse {
	if o == nil {
		return nil
	}
	return o.DeliveryResponse
}
