// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/webhooks/pkg/client/internal/utils"
	"github.com/formancehq/webhooks/pkg/client/models/components"
)

type GetDeliveryAttemptsRequest struct {
	ID       string  `pathParam:"style=simple,explode=false,name=id"`
	Cursor   *string `queryParam:"style=form,explode=true,name=cursor"`
	PageSize *int64  `default:"100" queryParam:"style=form,explode=true,name=pageSize"`
}

func (g GetDeliveryAttemptsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetDeliveryAttemptsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetDeliveryAttemptsRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetDeliveryAttemptsRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *GetDeliveryAttemptsRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type GetDeliveryAttemptsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated append-only attempt history.
	DeliveryAttemptsResponse *components.DeliveryAttemptsResponse
}

func (o *GetDeliveryAttemptsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetDeliveryAttemptsResponse) GetDeliveryAttemptsResponse() *components.DeliveryAttemptsResponse {
	if o == nil {
		return nil
	}
	return o.DeliveryAttemptsResponse
}
