// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/webhooks/pkg/client/models/components"
)

type InsertConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Config created successfully.
	ConfigResponse *components.ConfigResponse
}

func (o *InsertConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *InsertConfigResponse) GetConfigResponse() *components.ConfigResponse {
	if o == nil {
		return nil
	}
	return o.ConfigResponse
}
