// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/webhooks/pkg/client/models/components"
)

type ReplayDeliveriesRequest struct {
	IdempotencyKey          string                             `header:"style=simple,explode=false,name=Idempotency-Key"`
	ReplayDeliveriesRequest components.ReplayDeliveriesRequest `request:"mediaType=application/json"`
}

func (o *ReplayDeliveriesRequest) GetIdempotencyKey() string {
	if o == nil {
		return ""
	}
	return o.IdempotencyKey
}

func (o *ReplayDeliveriesRequest) GetReplayDeliveriesRequest() components.ReplayDeliveriesRequest {
	if o == nil {
		return components.ReplayDeliveriesRequest{}
	}
	return o.ReplayDeliveriesRequest
}

type ReplayDeliveriesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Deliveries synchronously placed back in the durable queue.
	ReplayDeliveriesResponse *components.ReplayDeliveriesResponse
}

func (o *ReplayDeliveriesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ReplayDeliveriesResponse) GetReplayDeliveriesResponse() *components.ReplayDeliveriesResponse {
	if o == nil {
		return nil
	}
	return o.ReplayDeliveriesResponse
}
