// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/webhooks/pkg/client/models/components"
)

type ReplayDeliveryRequest struct {
	ID             string `pathParam:"style=simple,explode=false,name=id"`
	IdempotencyKey string `header:"style=simple,explode=false,name=Idempotency-Key"`
}

func (o *ReplayDeliveryRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ReplayDeliveryRequest) GetIdempotencyKey() string {
	if o == nil {
		return ""
	}
	return o.IdempotencyKey
}

type ReplayDeliveryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Delivery synchronously placed back in the durable queue.
	DeliveryResponse *components.DeliveryResponse
}

func (o *ReplayDeliveryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ReplayDeliveryResponse) GetDeliveryResponse() *components.DeliveryResponse {
	if o == nil {
		return nil
	}
	return o.DeliveryResponse
}
