// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/webhooks/pkg/client/models/components"
)

type TestConfigRequest struct {
	// Config ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *TestConfigRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type TestConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AttemptResponse *components.AttemptResponse
}

func (o *TestConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *TestConfigResponse) GetAttemptResponse() *components.AttemptResponse {
	if o == nil {
		return nil
	}
	return o.AttemptResponse
}
