// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package client

type Webhooks struct {
	V1 *V1

	sdkConfiguration sdkConfiguration
}

func newWebhooks(sdkConfig sdkConfiguration) *Webhooks {
	return &Webhooks{
		sdkConfiguration: sdkConfig,
		V1:               newV1(sdkConfig),
	}
}
