name: Lint & Test
on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: 1.18
        description: "Go version to use for the tests"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
      - uses: actions/checkout@v3
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Install tools
        run: task install
      - name: Run lint & test
        run: task lint test
        env:
          MONGODB_CONN_STRING: "mongodb://admin:admin@localhost:27017/"
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
