on:
  push:
    branches:
      - main

name: main
jobs:
  lint:
    uses: numary/gh-workflows/.github/workflows/golang-lint.yml@main
    with:
      go_version: 1.18

  test:
    uses: ./.github/workflows/test.yaml
    needs:
      - lint
    with:
      go_version: 1.18

  build:
    uses: numary/gh-workflows/.github/workflows/docker-build.yml@main
    needs:
      - test
    with:
      go_version: 1.18
      service: webhooks
      version: develop
      sha: ${{ github.sha }}
      env: staging
    secrets:
      NUMARY_GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}

  build-main:
    uses: numary/gh-workflows/.github/workflows/docker-build.yml@main
    with:
      go_version: 1.18
      service: webhooks
      version: develop
      sha: ${{ github.sha }}
      env: main
    secrets:
      NUMARY_GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}

  deploy:
    needs:
      - build
    uses: numary/gh-workflows/.github/workflows/deploy-staging.yml@main
    with:
      service: webhooks
      version: pull-webhooks-${{ github.sha }}
    secrets:
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_STAGING }}
