on:
  push:
    branches:
      - main

name: main
jobs:
  lint:
    uses: numary/gh-workflows/.github/workflows/golang-lint.yml@main

  tests:
    uses: ./.github/workflows/tests.yml

  build-main:
    uses: numary/gh-workflows/.github/workflows/docker-build.yml@main
    needs:
      - lint
      - tests
    with:
      service: webhooks
      version: develop
      sha: ${{ github.sha }}
      env: main
    secrets:
      NUMARY_GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}

  build-staging:
    uses: numary/gh-workflows/.github/workflows/docker-build.yml@main
    needs:
      - lint
      - tests
    with:
      service: webhooks
      version: develop
      sha: ${{ github.sha }}
      env: staging
    secrets:
      NUMARY_GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}

  deploy-staging:
    needs:
      - build-staging
    uses: numary/gh-workflows/.github/workflows/deploy-staging.yml@main
    with:
      service: webhooks
      version: pull-webhooks-${{ github.sha }}
    secrets:
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_STAGING }}
