name: Pull Request - Open
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  infracost:
    uses: numary/gh-workflows/.github/workflows/infracost-staging.yml@main
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

  pr-style:
    uses: numary/gh-workflows/.github/workflows/pr-style.yml@main

  lint:
    uses: numary/gh-workflows/.github/workflows/golang-lint.yml@main

  tests:
    uses: ./.github/workflows/tests.yml
