on:
  push:
    branches-ignore:
      - main

name: Push
jobs:
  build-staging:
    uses: numary/gh-workflows/.github/workflows/docker-build.yml@main
    with:
      service: webhooks
      version: develop
      sha: ${{ github.sha }}
      env: staging
    secrets:
      NUMARY_GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}
