name: Tests
on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Install task
        uses: arduino/setup-task@v1
      - name: Install benthos
        run: task install:benthos
      - name: Run tests
        run: task tests
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
