name: Test
on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: 1.18
        description: "Go version to use for the tests"

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
    steps:
      - uses: actions/checkout@v3
      - name: Install Task
        uses: arduino/setup-task@v1
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
      - name: Run tests
        run: task test
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
