name: Tests
on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: 1.18
        description: "Go version to use for the tests"

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
      - uses: actions/checkout@v3
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Install benthos
        run: task install:benthos
      - name: Run tests
        run: task tests
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
